# Generated by Django 5.2 on 2025-07-04 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[("rent", "For Rent"), ("sale", "For Sale")],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bhk",
                    models.CharField(
                        choices=[
                            ("1", "1 BHK"),
                            ("2", "2 BHK"),
                            ("3", "3 BHK"),
                            ("4", "4 BHK"),
                            ("5+", "5+ BHK"),
                        ],
                        max_length=3,
                    ),
                ),
                ("area", models.IntegerField(help_text="Area in square feet")),
                (
                    "furnished",
                    models.CharField(
                        choices=[
                            ("furnished", "Furnished"),
                            ("semi_furnished", "Semi-Furnished"),
                            ("unfurnished", "Unfurnished"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("area_name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("pincode", models.CharField(max_length=10)),
                ("bathrooms", models.IntegerField(default=1)),
                ("balconies", models.IntegerField(default=0)),
                ("parking", models.BooleanField(default=False)),
                (
                    "main_image",
                    models.ImageField(blank=True, upload_to="property_images/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="property_images/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.property",
                    ),
                ),
            ],
        ),
    ]
